spring:
  application:
    name: code-snippet
  redis:
    username: root
    database: 0
    host: localhost
    port: 6379
  cloud:
    nacos:
      config:
        import-check:
          enabled: false