spring:
  redis:
    username: root
    database: 0
    host: ${REDIS_HOST:host.docker.internal}
    port: ${REDIS_PORT:6379}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://host.docker.internal:3306/chappter01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

nacos-dynamic-config:
  id: 5


