spring:
  redis:
    username: root
    database: 0
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/chappter01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

nacos-dynamic-config:
  id: 5


