name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Java 环境
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # 运行 Maven 构建
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      # 登录 ACR
      - name: Login to Alibaba Cloud ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: crpi-59dck2xo598rybsz.cn-shenzhen.personal.cr.aliyuncs.com
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}

      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        run: |
          cd code-practice-service
          docker build -t crpi-59dck2xo598rybsz.cn-shenzhen.personal.cr.aliyuncs.com/nextify/code-snippet:${{ github.sha }} .
          docker push crpi-59dck2xo598rybsz.cn-shenzhen.personal.cr.aliyuncs.com/nextify/code-snippet:${{ github.sha }}